---
- name: install apache2-suexec-custom
  apt: name=apache2-suexec-custom update_cache=yes
- name: enable rewrite apache2 module
	apache2_module: state=present name=rewrite
- name: enable deflate apache2 module
	apache2_module: state=present name=rewrite
- name: enable setenvif apache2 module
  apache2_module: state=present name=setenvif
- name: enable headers apache2 module
  apache2_module: state=present name=headers
- name: enable filter apache2 module
  apache2_module: state=present name=filter
- name: enable expires apache2 module
  apache2_module: state=present name=expires
- name: enable autoindex apache2 module
  apache2_module: state=present name=autoindex
- name: enable alias apache2 module
	apache2_module: state=present name=alias
- name: enable suexec apache2 module
	apache2_module: state=present name=suexec
- name: enable ssl apache2 module
	apache2_module: state=present name=ssl